// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'detail_tracks_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

DetailTracksModel _$DetailTracksModelFromJson(Map<String, dynamic> json) =>
    DetailTracksModel(
          altitudeAtStartAndFinish: json['Altitude at start and finish'] as String?,
          altitudeAtStartAndFinish1: json['Altitudeatstartandfinish'] as String?,
          startingAndFinishingAltitude: json['Starting and Finishing Altitude'] as String?,
          startingPoint: json['Starting Point'] as String?,
          description: json['Description'] as String?,
          distance: json['Distance'] as String?,
          history: json['History'] as String?,
          length: json['Length'] as String?,
          maps: json['Maps'] as String?,
          maxAltitude: json['Max Altitude'] as String?,
          startPoint: json['Start Point'] as String?,
          endPoint: json['End Point'] as String?,
          bestSeason: json['Best Season'] as String?,
          height: json['Height'] as String?,
          maximumHeight: json['Maximum height'] as String?,
          maximumHeight1: json['Maximum Height'] as String?,
          months: json['Months'] as String?,
          overView: json['Overview'] as String?,
          standard: json['Standard'] as String?,
          zone: json['Zone'] as String?,
          filterName: json['filtername'] as String?,
          name: json['name'] as String?,
          maximumAltitude: json['Maximum Altitude'] as String?,
          startEndAltitude: json['Start/End Altitude'] as String?,
          startAndFinish: json['Start and finish'] as String?,
          level: json['Level'] as String?,
          guideRequirement: json['Guide Requirement'] as String?,
          duration: json['Duration'] as String?,
          books: json['Books'] as String?,
          difficulty: json['Difficulty'] as String?,
          recommendedMaps: json['Recommended Maps'] as String?,
          time: json['time'] as String?,
          bestTime: json['Best Time'] as String?,
          difficultyLevel: json['Difficulty level'] as String?,
          elevation: json['Elevation'] as String?,
          startingAltitude: json['Starting Altitude'] as String?,
          altitudeAtStart: json['Altitude at Start'] as String?,
          altitudeAtFinish: json['Altitude at Finish'] as String?,
          recommendedTravelMethod: json['Recommended Travel Method'] as String?,
          mapReferences: json['Map References'] as String?,
          activities: json['Activities'] as String?,
          trekStandard: json['Trek Standard'] as String?,
          environmentalAndHistoricalContext: json['Environmental and Historical Context'] as String?,
          elevationAtStart: json['Elevation at Start'] as String?,
          elevationAtFinish: json['Elevation at Finish'] as String?,
          bestMonths: json['Best Months'] as String?,
          culturalAndHistoricalInsights: json['Cultural & Historical Insights'] as String?,
          husheValleyOverview: json['Hushé Valley Overview'] as String?,
          stages: json['Stages'] as String?,
    );
Map<String, dynamic> _$DetailTracksModelToJson(DetailTracksModel instance) =>
    <String, dynamic>{
          'Altitude at start and finish':instance.altitudeAtStartAndFinish,
          'Altitudeatstartandfinish':instance.altitudeAtStartAndFinish1,
          'Starting and Finishing Altitude':instance.startingAndFinishingAltitude,
          'Starting Point':instance.startingPoint,
          'Description':instance.description,
          'Distance':instance.distance,
          'History':instance.history,
          'Length':instance.length,
          'Maps':instance.maps,
          'Start Point':instance.startPoint,
          'Max Altitude':instance.maxAltitude,
          'End Point':instance.endPoint,
          'Best Season':instance.bestSeason,
          'Height':instance.height,
          'Maximum height':instance.maximumHeight,
          'Maximum Height':instance.maximumHeight1,
          'Months':instance.months,
          'Overview':instance.overView,
          'Standard':instance.standard,
          'Zone':instance.zone,
          'filtername':instance.filterName,
          'name':instance.name,
          'Maximum Altitude':instance.maximumAltitude,
          'Start/End Altitude':instance.startEndAltitude,
          'Start and finish':instance.startAndFinish,
          'Level':instance.level,
          'Guide Requirement':instance.guideRequirement,
          'Duration':instance.duration,
          'Books':instance.books,
          'Difficulty':instance.difficulty,
          'Recommended Maps':instance.recommendedMaps,
          'time':instance.time,
          'Best Time':instance.bestTime,
          'Difficulty level':instance.difficultyLevel,
          'Elevation':instance.elevation,
          'Starting Altitude':instance.startingAltitude,
          'Activities':instance.activities,
          'Trek Standard':instance.trekStandard,
          'Environmental and Historical Context':instance.environmentalAndHistoricalContext,
          'Elevation at Start':instance.elevationAtStart,
          'Elevation at Finish':instance.elevationAtFinish,
          'Best Months':instance.bestMonths,
          'Cultural & Historical Insights':instance.culturalAndHistoricalInsights,
          'Hushé Valley Overview':instance.husheValleyOverview,
          'Stages':instance.stages,
    };
